import dynamic from "next/dynamic";
import { Client, Message } from "@/Components";
const ChakraProviderUI = dynamic(() => import("../utils/ChakraProviderUI"));
const ReduxProvider = dynamic(
  () => import("../redux/reduxProvider/ReduxProvider")
);
import "./globals.css";
import { Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${roboto.className} `}>
        <ReduxProvider>
          <ChakraProviderUI>
            <ToastContainer position="bottom-left" />
            <Client>{children}</Client>
            <div className="fixed bottom-0  right-0 mx-auto z-50">
              <Message />
            </div>
          </ChakraProviderUI>
        </ReduxProvider>
      </body>
    </html>
  );
}
