import { Footer, Navbar, Message } from "@/Components";
import "./globals.css";
import type { Metadata } from "next";
import ChakraProviderUI from "@/utils/ChakraProviderUI";
import { Roboto } from "next/font/google";
import ReduxProvider from '@/redux/reduxProvider/ReduxProvider'
import {Toaster} from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${roboto.className} `}>
        <ReduxProvider>
        <ChakraProviderUI>
        <Toaster position="bottom-left" />
          <Navbar />
          {children}
          <div className="fixed bottom-0  right-0 mx-auto z-50">
            <Message />
          </div>
          <Footer />
        </ChakraProviderUI>
        </ReduxProvider>
      </body>
    </html>
  );
}
