import img1 from "../public/1.jpg";
import img38 from "../public/38.jpg";
import img31 from "../public/31.jpg";
import img4 from "../public/4.jpg";
import img5 from "../public/5.jpg";
import img6 from "../public/6.jpg";
import img39 from "../public/39.jpg";
import img8 from "../public/8.jpg";
import p1 from "../public/people-01.png";
import p2 from "../public/people-02.png";
import p3 from "../public/people-03.png";
import gig1 from "../public/gig1.jpg";
import gig2 from "../public/gig2.jpg";
import gig3 from "../public/gig3.jpg";

export const SliderData = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: img1.src,
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: img38.src,
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: img31.src,
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: img4.src,
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: img5.src,
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: img6.src,
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: img39.src,
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: img8.src,
  },
];

export const topRated = [
  {
    id: 1,
    name: "Dexterols",
    rating: 4.8,
    desc: "Experienced WordPress developer providing custom website solutions.",
    numOrders: 120,
    category: "Web Development",
    status: "Top Rated",
    img: p1.src,
    pricing: "PKR 80,000 - PKR 160,000",
    coverImg: gig1.src,
  },
  {
    id: 2,
    name: "Smith",
    rating: 4.9,
    desc: "DevOps specialist with a focus on automation and continuous integration.",
    numOrders: 90,
    category: "DevOps",
    status: "Level 2",
    img: p2.src,
    pricing: "PKR 50,000 - PKR 120,000",
    coverImg: gig2.src,
  },
  {
    id: 3,
    name: "Arslan akhtar",
    rating: 4.7,
    desc: "Skilled frontend developer creating user-friendly and responsive web interfaces.",
    numOrders: 150,
    category: "Web Development",
    status: "Pro",
    img: p3.src,
    pricing: "PKR 5,000 - PKR 20,000 ",
    coverImg: gig3.src,
  },
];
export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
    category: "GraphicsDesign",
    subcategory: "TypographyIllustration",
    OrdersCompleted: 10,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
    category: "GraphicsDesign",
    subcategory: "WebDesign",
    OrdersCompleted: 30,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
    category: "AIServices",
    subcategory: "NaturalLanguageProcessing(NLP)Services",
    OrdersCompleted: 1,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
    category: "AIServices",
    subcategory: "ComputerVisionSolutions",
    OrdersCompleted: 100,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
    category: "GraphicsDesign",
    subcategory: "3DModelingandRendering",
    OrdersCompleted: 24,
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard",
    category: "GraphicsDesign",
    subcategory: "SocialMediaGraphics",
    OrdersCompleted: 40,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
    category: "AIServices",
    subcategory: "AIinCustomerService",
    OrdersCompleted: 60,
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
    category: "WebDevelopment",
    subcategory: "Front-EndDevelopment",
    OrdersCompleted: 3,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 199,
    star: 4,
    username: "Johnny",
    category: "AIServices",
    subcategory: "ComputerVisionSolutions",
    OrdersCompleted: 10,
  },
];



export const Category = [
  {
    category: "WebDevelopment",
    imageUrl: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    subfields: [
      "Front-EndDevelopment",
      "Back-EndDevelopment",
      "UI/UXDesign",
      "E-CommerceDevelopment",
      "WordPressDevelopment",
    ],
    TotalNoofGigsAvailable: 10,
    SubCategoryNo: {
      "Front-EndDevelopment": 2,
      "Back-EndDevelopment": 3,
      "UI/UXDesign": 2,
      "E-CommerceDevelopment": 1,
      "WordPressDevelopment": 2,
    },
  },
  {
    category: "GraphicsDesign",
    imageUrl: "https://images.pexels.com/photos/2860810/pexels-photo-2860810.jpeg?auto=compress&cs=tinysrgb&w=600",
    subfields: [
      "TypographyIllustration",
      "WebDesign",
      "LogoDesigns",
      "SocialMediaGraphics",
      "3DModelingandRendering",
    ],
    TotalNoofGigsAvailable: 20,
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    SubCategoryNo: {
      "TypographyIllustration": 5,
      "WebDesign": 4,
      "LogoDesigns": 3,
      "SocialMediaGraphics": 4,
      "3DModelingandRendering": 4,
    },
  },
  {
    category: "DigitalMarketing",
    subfields: [
      "SearchEngineOptimization(SEO)",
      "ContentMarketing",
      "Pay-Per-Click(PPC)Advertising",
      "MarketingAutomation",
      "SocialMediaMarketing",
    ],
    imageUrl: "https://images.pexels.com/photos/4515793/pexels-photo-4515793.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    TotalNoofGigsAvailable: 5,
    SubCategoryNo: {
      "SearchEngineOptimization(SEO)": 1,
      "ContentMarketing": 2,
      "Pay-Per-Click(PPC)Advertising": 1,
      "MarketingAutomation": 1,
      "SocialMediaMarketing": 0,
    },
  },
  {
    category: "WritingTranslation",
    subfields: [
      "TechnicalWriting",
      "GhostWriting",
      "ContentWriting",
      "CreativeWriting",
      "CopyWriting",
    ],
    imageUrl: "https://images.pexels.com/photos/3539899/pexels-photo-3539899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    TotalNoofGigsAvailable: 15,
    SubCategoryNo: {
      "TechnicalWriting": 3,
      "GhostWriting": 4,
      "ContentWriting": 4,
      "CreativeWriting": 2,
      "CopyWriting": 2,
    },
  },
  {
    category: "VideoAnimation",
    subfields: [
      "2DAnimations",
      "3DAnimations",
      "InfographicVideos",
      "VirtualReality(VR)Animation",
      "CharacterAnimation",
    ],
    TotalNoofGigsAvailable: 7,
    imageUrl: "https://images.pexels.com/photos/827209/pexels-photo-827209.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    SubCategoryNo: {
      "2DAnimations": 2,
      "3DAnimations": 1,
      "InfographicVideos": 1,
      "VirtualReality(VR)Animation": 2,
      "CharacterAnimation": 1,
    },
  },
  {
    category: "AIServices",
    subfields: [
      "NaturalLanguageProcessing(NLP)Services",
      "ComputerVisionSolutions",
      "InfographicVideos",
      "AIinCustomerService",
      "MachineLearningModelDevelopment",
    ],
    imageUrl: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    TotalNoofGigsAvailable: 12,
    SubCategoryNo: {
      "NaturalLanguageProcessing(NLP)Services": 3,
      "ComputerVisionSolutions": 3,
      "InfographicVideos": 2,
      "AIinCustomerService": 2,
      "MachineLearningModelDevelopment": 2,
    },
  },
  {
    category: "SoftwareQualityAssurance",
    subfields: [
      "FunctionalTesting",
      "Non-functionalTesting",
      "UserAcceptanceTesting(UAT)",
      "QualityMetricsandMeasurement",
      "AlphaandBetaTesting",
    ],
    imageUrl: "https://images.pexels.com/photos/374559/pexels-photo-374559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    TotalNoofGigsAvailable: 3,
    SubCategoryNo: {
      "FunctionalTesting": 1,
      "Non-functionalTesting": 0,
      "UserAcceptanceTesting(UAT)": 1,
      "QualityMetricsandMeasurement": 0,
      "AlphaandBetaTesting": 1,
    },
  },
];
